"""Shared input, path and upload safety helpers.

The API stores user-generated media on the local filesystem.  Keeping the
normalisation rules in one module prevents individual routes from accidentally
re-introducing path traversal or unbounded body reads.
"""

from __future__ import annotations

import os
import re
import socket
import stat
import uuid
import zipfile
from collections.abc import Iterable
from pathlib import Path, PurePosixPath
from urllib.parse import urljoin, urlparse

import httpx


class UploadLimitExceeded(ValueError):
    """Raised when an uploaded body exceeds its configured limit."""


_SAFE_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$")
_DOCX_MAX_ENTRIES = 2048
_DOCX_MAX_MEMBER_BYTES = 32 * 1024 * 1024
_DOCX_MAX_EXPANDED_BYTES = 64 * 1024 * 1024
_DOCX_MAX_COMPRESSION_RATIO = 200


def validate_identifier(value: str, field: str = "id") -> str:
    """Validate a value that will be used as a path component.

    Project and shot IDs generated by the application are UUID-like strings,
    while legacy installations may use an underscore suffix.  The deliberately
    small ASCII alphabet supports both formats and excludes separators,
    traversal components, control characters and excessively long names.
    """

    candidate = str(value or "").strip()
    if not candidate or candidate in {".", ".."} or not _SAFE_ID.fullmatch(candidate):
        raise ValueError(f"非法{field}")
    return candidate


def safe_path(root: str | Path, *parts: str, create_parent: bool = False) -> Path:
    """Return a path guaranteed to remain below ``root``.

    All components are validated as identifiers.  ``resolve(strict=False)``
    catches symlink escapes for existing components as well as ``..`` in new
    paths.  Callers can request parent creation after the check.
    """

    root_path = Path(root).expanduser().resolve()
    target = root_path
    for part in parts:
        target = target / validate_identifier(part, "路径组件")
    resolved = target.resolve(strict=False)
    try:
        resolved.relative_to(root_path)
    except ValueError as exc:
        raise ValueError("路径超出允许目录") from exc
    if create_parent:
        resolved.parent.mkdir(parents=True, exist_ok=True)
    return resolved


def safe_filename(filename: str | None, allowed_extensions: Iterable[str] | None = None) -> tuple[str, str]:
    """Return a basename and normalised extension for an uploaded filename."""

    raw = str(filename or "").replace("\\", "/")
    name = Path(raw).name
    if not name or name in {".", ".."} or "\x00" in name:
        raise ValueError("文件名非法")
    extension = Path(name).suffix.lower()
    allowed = {str(item).lower() for item in (allowed_extensions or ())}
    if allowed and extension not in allowed:
        raise ValueError("不支持的文件类型")
    # The original name is never used as a directory component.  Keep only a
    # conservative basename for diagnostics; stored files use server names.
    return name[:255], extension


async def save_upload_stream(upload, destination: str | Path, max_bytes: int, chunk_size: int = 1024 * 1024) -> int:
    """Stream an UploadFile to disk, atomically replacing the destination.

    A temporary sibling file is removed on any failure.  The caller can safely
    parse ``destination`` only after this function returns.
    """

    target = Path(destination)
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_name(f".{target.name}.{uuid.uuid4().hex}.upload")
    total = 0
    try:
        with temporary.open("wb") as output:
            while True:
                chunk = await upload.read(chunk_size)
                if not chunk:
                    break
                total += len(chunk)
                if total > max_bytes:
                    raise UploadLimitExceeded(f"上传文件超过 {max_bytes} 字节限制")
                output.write(chunk)
            output.flush()
            os.fsync(output.fileno())
        os.replace(temporary, target)
        return total
    finally:
        try:
            temporary.unlink(missing_ok=True)
        except OSError:
            pass


def validate_script_upload(path: str | Path, extension: str, content_type: str | None) -> None:
    """Validate the declared type and inexpensive signature of a script upload."""

    mime = (content_type or "").split(";", 1)[0].strip().lower()
    allowed_mimes = {
        ".txt": {"text/plain", "text/markdown", "application/octet-stream", ""},
        ".md": {"text/plain", "text/markdown", "application/octet-stream", ""},
        ".markdown": {"text/plain", "text/markdown", "application/octet-stream", ""},
        ".docx": {
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "application/octet-stream",
            "",
        },
    }
    if mime not in allowed_mimes.get(extension.lower(), set()):
        raise ValueError("上传文件 MIME 类型不匹配")
    with Path(path).open("rb") as source:
        header = source.read(4096)
    if extension.lower() == ".docx":
        if not header.startswith(b"PK\x03\x04"):
            raise ValueError("上传文件不是有效的 DOCX")
        _validate_docx_archive(path)
    elif b"\x00" in header:
        raise ValueError("文本剧本包含二进制内容")


def _validate_docx_archive(path: str | Path) -> None:
    """Reject hostile OOXML archives before python-docx expands XML parts."""

    try:
        with zipfile.ZipFile(path) as archive:
            members = archive.infolist()
    except (OSError, zipfile.BadZipFile, zipfile.LargeZipFile) as exc:
        raise ValueError("上传文件不是有效的 DOCX") from exc

    if not members or len(members) > _DOCX_MAX_ENTRIES:
        raise ValueError("DOCX 包含过多文件")

    names: set[str] = set()
    expanded_bytes = 0
    for member in members:
        name = member.filename
        normalized = PurePosixPath(name)
        if (
            not name
            or "\x00" in name
            or "\\" in name
            or name.startswith(("/", "\\"))
            or re.match(r"^[A-Za-z]:", name)
            or any(part in {"", ".", ".."} for part in normalized.parts)
            or normalized.as_posix() != name.rstrip("/")
        ):
            raise ValueError("DOCX 包含非法文件路径")
        if name in names:
            raise ValueError("DOCX 包含重复文件路径")
        names.add(name)

        unix_mode = member.external_attr >> 16
        if stat.S_ISLNK(unix_mode):
            raise ValueError("DOCX 不允许包含符号链接")
        if member.flag_bits & 0x1:
            raise ValueError("DOCX 不允许包含加密文件")
        if member.is_dir():
            continue
        if member.file_size > _DOCX_MAX_MEMBER_BYTES:
            raise ValueError("DOCX 文件展开后过大")
        expanded_bytes += member.file_size
        if expanded_bytes > _DOCX_MAX_EXPANDED_BYTES:
            raise ValueError("DOCX 展开后总大小超过限制")
        if member.file_size:
            if member.compress_size <= 0 or member.file_size > member.compress_size * _DOCX_MAX_COMPRESSION_RATIO:
                raise ValueError("DOCX 压缩比异常")

    if "[Content_Types].xml" not in names or "word/document.xml" not in names:
        raise ValueError("上传文件不是有效的 DOCX")


def validate_video_upload(path: str | Path, content_type: str | None) -> None:
    """Validate an MP4/M4V MIME declaration and ISO BMFF file signature."""

    mime = (content_type or "").split(";", 1)[0].strip().lower()
    if mime not in {"video/mp4", "video/x-m4v", "application/octet-stream", ""}:
        raise ValueError("上传文件 MIME 类型不是 MP4/M4V")
    with Path(path).open("rb") as source:
        header = source.read(64)
    if b"ftyp" not in header:
        raise ValueError("上传文件不是有效的 MP4 视频")


def existing_file(path: str | Path, *, minimum_size: int = 1, allowed_roots: Iterable[str | Path] = ()) -> Path | None:
    """Resolve a local media path and ensure it is a regular bounded file."""

    candidate = Path(path)
    if not candidate.is_absolute():
        # Stored paths are normally absolute, but older rows contain paths
        # relative to the repository root.
        candidate = Path.cwd() / candidate
    try:
        resolved = candidate.resolve(strict=True)
    except (FileNotFoundError, OSError, RuntimeError):
        return None
    if not resolved.is_file():
        return None
    roots = [Path(root).resolve() for root in allowed_roots]
    if roots:
        try:
            if not any(resolved.is_relative_to(root) for root in roots):
                return None
        except AttributeError:  # pragma: no cover - Python < 3.9 fallback
            if not any(str(resolved).startswith(str(root) + os.sep) for root in roots):
                return None
    try:
        if resolved.stat().st_size < minimum_size:
            return None
    except OSError:
        return None
    return resolved


def atomic_write_bytes(destination: str | Path, content: bytes, *, minimum_size: int = 0) -> Path:
    """Write generated media atomically and reject unexpectedly empty output."""

    if len(content) < minimum_size:
        raise ValueError("生成文件为空或过小")
    target = Path(destination)
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_name(f".{target.name}.{uuid.uuid4().hex}.tmp")
    try:
        temporary.write_bytes(content)
        os.replace(temporary, target)
    finally:
        temporary.unlink(missing_ok=True)
    return target


def _normalise_remote_hostname(hostname: str) -> str:
    """Return the ASCII form used by HTTP clients for hostname lookups."""

    try:
        return hostname.rstrip(".").encode("idna").decode("ascii").lower()
    except UnicodeError as exc:
        raise ValueError("远程资源域名非法") from exc


def _validate_remote_target(url: str) -> tuple[str, str, tuple[str, ...]]:
    """Validate a URL and return its hostname plus the approved IP addresses."""

    value = str(url or "").strip()
    parsed = urlparse(value)
    if parsed.scheme not in {"http", "https"} or not parsed.hostname or parsed.username or parsed.password:
        raise ValueError("远程资源 URL 非法")
    hostname = _normalise_remote_hostname(parsed.hostname)
    if hostname in {"localhost", "localhost.localdomain"} or hostname.endswith(".local"):
        raise ValueError("禁止访问本机或内网资源")
    try:
        addresses = tuple(
            dict.fromkeys(item[4][0] for item in socket.getaddrinfo(hostname, parsed.port, type=socket.SOCK_STREAM))
        )
    except OSError as exc:
        raise ValueError("远程资源域名无法解析") from exc
    if not addresses:
        raise ValueError("远程资源域名无法解析")
    for address in addresses:
        try:
            import ipaddress

            ip = ipaddress.ip_address(address)
            if (
                ip.is_private
                or ip.is_loopback
                or ip.is_link_local
                or ip.is_reserved
                or ip.is_multicast
                or ip.is_unspecified
            ):
                raise ValueError("禁止访问本机或内网资源")
        except ValueError as exc:
            # Preserve our explicit policy error; malformed addresses are also
            # rejected rather than passed to the HTTP client.
            if "禁止访问" in str(exc):
                raise
            raise ValueError("远程资源地址非法") from exc
    return value, hostname, addresses


def validate_remote_url(url: str) -> str:
    """Allow public HTTP(S) URLs and reject local/private SSRF targets."""

    return _validate_remote_target(url)[0]


def _pinned_request_target(url: str, hostname: str, address: str) -> tuple[str, str]:
    """Build an IP-literal request URL while preserving the HTTP Host value."""

    parsed = urlparse(url)
    port = parsed.port
    address_authority = f"[{address}]" if ":" in address else address
    host_authority = f"[{hostname}]" if ":" in hostname else hostname
    if port is not None:
        address_authority = f"{address_authority}:{port}"
        default_port = 80 if parsed.scheme == "http" else 443
        if port != default_port:
            host_authority = f"{host_authority}:{port}"
    return parsed._replace(netloc=address_authority).geturl(), host_authority


async def download_remote_bytes(url: str, *, max_bytes: int, timeout: float = 180.0) -> bytes:
    """Download a bounded public resource with validated redirects."""

    current, hostname, addresses = _validate_remote_target(url)
    limits = httpx.Limits(max_connections=4, max_keepalive_connections=2)
    async with httpx.AsyncClient(
        timeout=timeout,
        follow_redirects=False,
        limits=limits,
        trust_env=False,
    ) as client:
        for _ in range(4):
            request_url, host_header = _pinned_request_target(current, hostname, addresses[0])
            async with client.stream(
                "GET",
                request_url,
                headers={"Host": host_header},
                extensions={"sni_hostname": hostname},
            ) as response:
                if response.status_code in {301, 302, 303, 307, 308}:
                    location = response.headers.get("location")
                    if not location:
                        raise ValueError("远程资源重定向缺少目标")
                    current, hostname, addresses = _validate_remote_target(urljoin(current, location))
                    continue
                response.raise_for_status()
                content_length = response.headers.get("content-length")
                if content_length and int(content_length) > max_bytes:
                    raise UploadLimitExceeded("远程资源超过大小限制")
                body = bytearray()
                async for chunk in response.aiter_bytes(1024 * 1024):
                    body.extend(chunk)
                    if len(body) > max_bytes:
                        raise UploadLimitExceeded("远程资源超过大小限制")
                return bytes(body)
    raise ValueError("远程资源重定向次数过多")


async def download_remote_file(
    url: str,
    destination: str | Path,
    *,
    max_bytes: int,
    timeout: float = 180.0,
) -> int:
    """Stream a validated remote asset to an atomically published file."""

    current, hostname, addresses = _validate_remote_target(url)
    target = Path(destination)
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_name(f".{target.name}.{uuid.uuid4().hex}.download")
    limits = httpx.Limits(max_connections=4, max_keepalive_connections=2)
    try:
        async with httpx.AsyncClient(
            timeout=timeout,
            follow_redirects=False,
            limits=limits,
            trust_env=False,
        ) as client:
            for _ in range(4):
                request_url, host_header = _pinned_request_target(current, hostname, addresses[0])
                async with client.stream(
                    "GET",
                    request_url,
                    headers={"Host": host_header},
                    extensions={"sni_hostname": hostname},
                ) as response:
                    if response.status_code in {301, 302, 303, 307, 308}:
                        location = response.headers.get("location")
                        if not location:
                            raise ValueError("远程资源重定向缺少目标")
                        current, hostname, addresses = _validate_remote_target(urljoin(current, location))
                        continue
                    response.raise_for_status()
                    content_length = response.headers.get("content-length")
                    if content_length and int(content_length) > max_bytes:
                        raise UploadLimitExceeded("远程资源超过大小限制")
                    total = 0
                    with temporary.open("wb") as output:
                        async for chunk in response.aiter_bytes(1024 * 1024):
                            total += len(chunk)
                            if total > max_bytes:
                                raise UploadLimitExceeded("远程资源超过大小限制")
                            output.write(chunk)
                        output.flush()
                        os.fsync(output.fileno())
                    os.replace(temporary, target)
                    return total
        raise ValueError("远程资源重定向次数过多")
    finally:
        try:
            temporary.unlink(missing_ok=True)
        except OSError:
            pass


__all__ = [
    "UploadLimitExceeded",
    "atomic_write_bytes",
    "download_remote_file",
    "download_remote_bytes",
    "existing_file",
    "safe_filename",
    "safe_path",
    "save_upload_stream",
    "validate_remote_url",
    "validate_identifier",
    "validate_script_upload",
    "validate_video_upload",
]
